export enum HTTPErrorCode {
  ERR_NO_AVAILABLE_PORT = 'ERR_NO_AVAILABLE_PORT',
  ERR_HTTP_NOT_SUPPORT_RAW = 'ERR_HTTP_NOT_SUPPORT_RAW',
  ERR_HTTP_NOT_SUPPORT_SEND_REQUEST = 'ERR_HTTP_NOT_SUPPORT_SEND_REQUEST',
  ERR_HTTP_CONNECTOR_ONLY_SPPORT_REQUEST = 'ERR_HTTP_CONNECTOR_ONLY_SPPORT_REQUEST',
}
